### ISSUE TITLE
[Bug on Typora] Markdown Meta Info Not Hidden in H1

### ISSUE THREAD

**Issue by ereyue** [ereyue/Suisei#2]
## Recheck

-   [x] I've already updated to the latest Typora version
-   [x] I've already updated to the latest Suisei version
-   [x] I found nothing related to this bug in the Wiki or Issues

## Screenshots

<img width="979" alt="image" src="https://user-images.githubusercontent.com/17521736/75951428-fdb1d300-5ee6-11ea-8b1a-345ddfb885ad.png">

<details>
    <summary>Console Log</summary>
    <p>
    <pre>
    Not related
    </pre>
    </p>
</details>

## Description

Meta elements didn't get hidden in the `<h1>`.

## To Reproduce

Add markdown elements, i.e., `**`, `*` or `![]()`  in `<h1>`.

## Expected Behavior

Behave just like in normal `<p>` tag.
